# File: .github/workflows/company-news.yml

name: Company News

on:
  push:
  # schedule:
  #   - cron: '0 0 * * 3,5' # Runs Wednesday and Friday at midnight UTC
  workflow_dispatch:

# Add this permissions section
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          python -m venv venv
          source ./venv/bin/activate
          python -m pip install -U duckduckgo-search pandas requests beautifulsoup4

      - name: Get company news
        run: |
          source ./venv/bin/activate
          
          # Create header for aggregated CSV with company as first column
          echo "company,date,title,body,url,image,source" > aggregated-news.csv
          
          # Process companies and append to CSV
          for company in 'Unaliwear' 'BrainCheck' 'Dermala' 'Oralucent' 'Flowly' 'Rosy' 'De Oro Devices' 'Partum Health' 'Fort Health' 'RubyWell' 'Atlantic Sea Farms' 'VidaFuel'; do
            echo "Processing $company..."
            # Normal processing with retry
            ddgs news -k "$company company" -m 2 -o "news-$company.csv" || 
            # Retry once if it fails
            (echo "Retrying $company..." && sleep 5 && ddgs news -k "$company company" -m 2 -o "news-$company.csv")
            
            # Check if CSV was created and has content (more than just header)
            if [ -f "news-$company.csv" ] && [ $(wc -l < "news-$company.csv") -gt 1 ]; then
              # Skip header row and add company as first column for each row
              awk -F, 'NR>1 {print "\"'$company'\","$0}' "news-$company.csv" >> aggregated-news.csv
              echo "Added $company news to aggregated CSV"
            else
              echo "Warning: No results for $company or CSV creation failed"
              # Create an empty CSV with just the header to prevent errors
              echo "date,title,body,url,image,source" > "news-$company.csv"
              # Add a placeholder entry in aggregated CSV
              echo "\"$company\",\"$(date +%Y-%m-%d)\",\"No recent news found for $company\",\"No content available\",\"#\",\"\",\"System\"" >> aggregated-news.csv
            fi
          done
          
          # Show summary
          echo "Aggregated news CSV created with $(( $(wc -l < aggregated-news.csv) - 1 )) entries"
      
      - name: Convert CSV to HTML
        run: |
          source ./venv/bin/activate
          python convert_to_html.py
      
      - name: Add files to Git
        run: |
          git config --local user.email "lloydchang@gmail.com"
          git config --local user.name "lloydchang"
          git add news-*.csv
          git add aggregated-news.csv
          git add index.html
          git add news_cache.json
      
      - name: Commit and push if changes
        run: |
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update news dashboard" && git push)
